name: Eslidear
favicon: null
layout_spectrum: 0.76382
typography_spectrum: 0.2929
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d29c37'
    - '#e9c15c'
    - '#be852e'
    - '#fae1bd'
    - '#bf7000'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
